project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summary/', include('summary.urls')),
]

summary/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('expenses/', views.expenses, name='expenses'),
    path('categories/', views.categories, name='categories'),
]

summary/models.py
from django.db import models
from django.forms import ModelForm
import json

# Create your models here.


class ExpenseCategories(models.Model):
    category = models.CharField(max_length=50, unique=True)
    planned_amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        #     return self.category, self.planned_amount
        return self.category


class MonthlySummary(models.Model):
    expense_date = models.DateField(null=True)
    amount = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, default=0)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(
        ExpenseCategories, to_field='category', on_delete=models.CASCADE, null=True)

    # def __str__(self):
    #     return self.category, self.amount


class Expenses(ModelForm):
    class Meta:
        model = MonthlySummary
        fields = ['expense_date', 'amount', 'description',
                  'category']


class Categories(ModelForm):
    class Meta:
        model = ExpenseCategories
        fields = ['category', 'planned_amount']

summary/views.py
from django.db.models.aggregates import Count, Max
from summary.models import Categories, ExpenseCategories, Expenses, MonthlySummary
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Sum, F, Count, Max, FloatField
import matplotlib.pyplot as plt
from io import StringIO
import numpy as np
from django.db import connection
from django.urls import reverse
from django.contrib import messages
# Create your views here.


def index(request):

    sql = f"""SELECT a.category, a.planned_amount,sum(b.amount) FROM summary_ExpenseCategories as a
    left join summary_MonthlySummary as b on b.category_id =a.category group by a.category"""
    cursor = connection.cursor()
    cursor.execute(sql)
    row = cursor.fetchall()

    total_planned = ExpenseCategories.objects.aggregate(
        total=Sum('planned_amount'))
    total_actual = MonthlySummary.objects.aggregate(
        total=Sum('amount'))

    graph = return_graph(total_planned['total'], total_actual['total'])

    context = {'total_actual': total_actual,
               'total_planned': total_planned, 'graph': graph, 'row': row}

    return render(request, 'summary/index.html', context)


def return_graph(x, y):
    fig, ax = plt.subplots()
    ax.bar(['Planned', 'Actual'], [x, y], color=['red', 'green'])
    ax.set_title('Your total expenses vs total budget')
    # fig = plt.figure()
    # ax = fig.add_axes([0, 0, .25, .25])
    # ax.bar(x, y)
    # plt.plot(x, y)

    imgdata = StringIO()
    fig.savefig(imgdata, format='svg')
    imgdata.seek(0)

    data = imgdata.getvalue()
    return data


def expenses(request):
    if request.method == 'POST':
        form = Expenses(request.POST)
        if form.is_valid():
            form.save()
            form = Expenses()
            messages.add_message(request, messages.INFO, 'Expense Added')
            # return HttpResponseRedirect(reverse('index'))
    else:
        form = Expenses()
    context = {'allrows': MonthlySummary.objects.order_by(
        "-pk"), 'form': form}
    return render(request, 'summary/expenses.html', context)


def categories(request):
    if request.method == 'POST':
        form = Categories(request.POST)
        if form.is_valid():
            form.save()
            form = Categories()
            messages.add_message(request, messages.INFO, 'Category Added')
            # return HttpResponseRedirect(reverse('index'))
    else:
        form = Categories()
    context = {'allrows': ExpenseCategories.objects.order_by(
        "-pk"), 'form': form}
    return render(request, 'summary/categories.html', context)

summary/templates/summary/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Budget</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css"> 
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light"> 
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/summary/">Expenses Summary</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/summary/expenses/">Add Expenses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/summary/categories/">Add Categories</a>
              </li>
          </ul>
          <form class="d-flex">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock %}

  </body>
</html>

summary/templates/summary/categories.html
{% extends 'summary/base.html' %}

{% block content %}

    <h2>Expense Categories</h2>

    <h6>Please use the following form to Add Expense Categories</h6>
    <form id="categories" action="{% url 'categories' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}  
        <input type="submit" value="Submit">
    </form>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }}  </li>
        {% endfor %}
        </ul>
{% endif %}
    <table class="table table-striped" id="summary">
        <thead>
          <tr>
            <th scope="col">Category</th>
            <th scope="col">Planned Amount</th>
          </tr>
        </thead>
        <tbody>
          {% for row in allrows %} 
          <tr>
            <td>{{ row.category }}</td>
            <td>{{ row.planned_amount }}</td>
          {% endfor %}
          </tr>
        </tbody>
      </table>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"
      ></script>
      <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
      <script>$(document).ready( function () {
        $('#summary').DataTable();
      } );</script>
    <script> 
        flatpickr("#id_expense_date", {enableTime: false, dateFormat: "Y-m-d"}); 
    </script>
    <script>document.getElementById('expense').reset();</script>

    {% endblock %}

summary/templates/summary/expenses.html
{% extends 'summary/base.html' %}

{% block content %}

    <h2>Expenses</h2>

    <h6>Please use the following form to submit Daily expenses</h6>
    <form id="expense" action="{% url 'expenses' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}  
        <input type="submit" value="Submit">
    </form>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }}  </li>
        {% endfor %}
        </ul>
{% endif %}
    <table class="table table-striped" id="summary">
        <thead>
          <tr>
            <th scope="col">Date</th>
            <th scope="col">Amount</th>
            <th scope="col">Description</th>
            <th scope="col">Category</th>
          </tr>
        </thead>
        <tbody>
          {% for row in allrows %} 
          <tr>
            <td>{{ row.expense_date }}</td>
            <td>{{ row.amount }}</td>
            <td>{{ row.description }}</td>
            <td>{{ row.category }}</td>
          {% endfor %}
          </tr>
        </tbody>
      </table>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"
      ></script>
      <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
      <script>$(document).ready( function () {
        $('#summary').DataTable();
      } );</script>
    <script> 
        flatpickr("#id_expense_date", {enableTime: false, dateFormat: "Y-m-d"}); 
    </script>
    <script>document.getElementById('expense').reset();</script>

    {% endblock %}

summary/templates/summary/index.html
{% extends 'summary/base.html' %}
{% load custom_tags %}

{% block content %}
    <h2>Summary</h2>

    <table class="table table-striped" id="summary">
      <thead>
        <tr>
          <th scope="col">Category</th>
          <th scope="col">Actual</th>
          <th scope="col">Planned</th>
          <th scope="col">Difference</th>
        </tr>
      </thead>
      <tbody>
        {% for r in row %} 
        <tr>
          <td>{{ r.0 }}</td>
          <td>{{ r.2 }}</td>
          <td>{{ r.1 }}</td>
          {% if r.2 == None  %}
            <td>None</td>
          {% else %}
            <td>{{ r.1|subtract:r.2 }}</td>
          {% endif %}
        {% endfor %}
        </tr>
        <tr>
          <td><b>Total</b></td>
          <td><b>{{ total_actual.total }}</b></td>
          <td><b>{{ total_planned.total }}</b></td>
          <td><b>{{ total_planned.total|subtract:total_actual.total }}</b></td>
        </tr>
      </tbody>
    
 
      {{ graph|safe }}
    </table>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
      crossorigin="anonymous"
    ></script>
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script>$(document).ready( function () {
      $('#summary').DataTable();
    } );</script>


{% endblock %}